/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minibae_Mixer */

#ifndef _Included_org_minibae_Mixer
#define _Included_org_minibae_Mixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minibae_Mixer
 * Method:    _newMixer
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_org_minibae_Mixer__1newMixer
  (JNIEnv *, jclass);

/*
 * Class:     org_minibae_Mixer
 * Method:    _deleteMixer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_minibae_Mixer__1deleteMixer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_minibae_Mixer
 * Method:    _openMixer
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1openMixer
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1disengageAudio
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1reengageAudio
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1isAudioEngaged
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1setDefaultReverb
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1addBankFromFile
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1setMasterVolume
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1setDefaultVelocityCurve
  (JNIEnv *, jclass, jint);

JNIEXPORT jstring JNICALL Java_org_minibae_Mixer__1getBankFriendlyName
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1addBankFromMemoryWithFilename
  (JNIEnv *, jclass, jlong, jbyteArray, jstring);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1startOutputToFile
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1serviceOutputToFile
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1stopOutputToFile
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
